-- 코드를 작성해주세요
SELECT HE.DEPT_ID, DEPT_NAME_EN, AVG_SAL
FROM (
    SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) AS HE
JOIN HR_DEPARTMENT AS HD
ON HE.DEPT_ID = HD.DEPT_ID
ORDER BY AVG_SAL DESC