-- 코드를 입력하세요
SELECT DISTINCT(CC.CAR_ID)
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) AS CC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
ON CC.CAR_ID = RH.CAR_ID
WHERE MONTH(START_DATE) = 10
ORDER BY CC.CAR_ID DESC