SELECT ANY_VALUE(HG.SCORE) AS SCORE, HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) AS HG
JOIN HR_EMPLOYEES AS HE
ON HG.EMP_NO = HE.EMP_NO
WHERE HG.SCORE = (SELECT MAX(SCORE) FROM (
                    SELECT SUM(SCORE) AS SCORE 
                    FROM HR_GRADE 
                    GROUP BY EMP_NO
                 ) AS MAX_SCORE);